### ISSUE TITLE
yr © og sånn

### ISSUE THREAD

**Issue by peroja** [jurgemaister/turid#40]
09:06 <@pengwen> http://api.yr.no/lisens_data.html
09:06 < Turid> "Betingelser for bruk av data"
09:09 < jmaister> oh
09:09 <@pengwen> ja, men må da finnes en liten vei rundt?
09:09 <@pengwen> hihi, pm med (c)-info?
09:10 < jmaister> Kommentar i koden? :P
09:10 <@pengwen> ja... kommentar i koden høres greit nok ut
09:10 < jmaister> Legger det ut med den nye pluginen
09:10 <@pengwen> lager jo boten som foss kun for å dele kode, ikke sette opp
                 tjenste?
09:10 < jmaister> jepp
09:10 < jmaister> seff
09:10 <@pengwen> også.... mulig....
09:11 <@pengwen> å stoppe de evige yr-floddene med litt sånn pm om man bruker
                 yr mer enn 3 ggr pr time
09:11 <@pengwen> en sånn pm kan fint være bloat :D
09:11 < jmaister> feel free :P
09:11 <@pengwen> ja
09:11 <@pengwen> :)
09:12 <@pengwen> oooh! epic bortforklaring! lager en ticket på det!

**Comment by jurgemaister** [comment]
http://api.yr.no/lisens_data.html

**Comment by jurgemaister** [comment]
Btw. please stick to English

**Comment by peroja** [comment]
Bedre sånn? https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2Fapi.yr.no%2Flisens_data.html
