### ISSUE TITLE
Flood protection on urlmagic

### ISSUE THREAD

**Issue by peroja** [jurgemaister/turid#50]
08:36 @matsj https://www.kickstarter.com/projects/1028379103/gnarbox-edit-and-share-hd-footage-in-seconds-lapto
08:36 < Turid> "GNARBOX: Edit & Share HD Footage in Seconds - Laptop
               Free by GNARBOX — Kickstarteralert iconarrow-down
               iconarrow-left iconarrow-right iconarrow-up
               iconbacker-badge iconbar-chart iconcalendar iconchat
               iconcheck iconclock iconclose iconclosed-caption
               iconcompose iconconversion icondirect-up icondownload
               icondrop-down iconexpand iconfacebook iconflag
               iconglobe icongrid iconheart iconhelp iconimage
               iconinfo iconinstagram iconkickstarter iconlink
               iconlocation iconlock ...
08:36 < Turid> ... iconmail iconmenu iconmove iconmusic iconpause
               iconpin iconpinterest iconplay iconplus-circle
               iconplus iconreport iconsearch iconshare iconstar
               iconstop icontag icontrash icontumblr icontwitter
               iconunlink iconuser iconvideo iconview-all iconvine
               iconvolume-up iconvolume iconwrite iconyoutube icon"
               (http://kck.st/1Jm3mkq)

**Comment by jurgemaister** [comment]
This is due to an embedded svg icon system where every svg has a <title> tag. Therefore, the bot should only fetch title within

    <html>
        <head>
            <title>Fetch me!</title>
        </head>

**Comment by peroja** [comment]
True, but i still think this is a good idea as Master Flood Gate[™]:
-                                 m.reply %-"#{title}" #{shortURL}- if count > (urlwords.count/2)
+                                 m.reply %-"#{title[0..300]}" #{shortURL}- if count > (urlwords.count/2)

**Comment by jurgemaister** [comment]
This was a bug in mechanize. Fixed with latest update

**Comment by peroja** [comment]
No cred 4 me, @jurgemaister?
