### ISSUE TITLE
uffda's karma forgotten

### ISSUE THREAD

**Issue by callumacrae** [jurgemaister/turid#58]
for some reason uffdas karma always goes back to zero even though i say uffda++ at least twice a day

**Comment by jurgemaister** [comment]
Find out why and fix it @callumacrae

**Comment by callumacrae** [comment]
13:10      bikebot2| ☆☆ uffda's karma is 6 ☆☆
 13:12      bikebot2| ☆☆ uffda's karma is 1 ☆☆

**Comment by callumacrae** [comment]
its broken

**Comment by jurgemaister** [comment]
Fixed in 96bf2b2c4374338b0639ef764563bc47d9df66ea, was a db issue
